export const workItems = [
  {
    heading: "GreenRoots Website",
    imgsrc: "/green-roots.webp",
    link: "https://www.greenrootscol.co/",
    github: "https://github.com/francwow/green-roots-next-js.git",
    id: 0,
    languages: "Nextjs | TypeScript | Tailwind CSS",
  },
  {
    heading: "Depósito San Antonio Website",
    imgsrc: "/deposito.webp",
    link: "https://www.depositosanantonio.com/",
    github: "https://github.com/francwow/DepositoSanAntonio-Website",
    id: 1,
    languages: "HTML | CSS",
  },
  {
    heading: "Latiendo Website",
    imgsrc: "/latiendo.webp",
    link: "https://www.latiendo.co/",
    github: "https://github.com/francwow/latiendo",
    id: 2,
    languages: "HTML | CSS | JavaScript",
  },

  {
    heading: "Hostal Sep7imo Arte Website",
    imgsrc: "/hostal.webp",
    link: "https://hostalsep7imoarte.com/",
    github: "https://github.com/francwow/hostal-septimoarte",
    id: 3,
    languages: "Nextjs | TypeScript | CSS",
  },
  {
    heading: "Donoso Films Website",
    imgsrc: "/donosofilms.webp",
    link: "https://www.donosofilms.com/",
    github: "https://github.com/francwow/donoso-films-nextjs",
    id: 4,
    languages: "Nextjs | TypeScript | CSS",
  },
  {
    heading: "Arthas Menethil tribute page",
    imgsrc: "/arthas.webp",
    link: "https://arthas-menethil.vercel.app/",
    github: "https://github.com/francwow/Arthas-Menethil",
    id: 5,
    languages: "HTML | CSS | JavaScript",
  },
  {
    heading: "First Portfolio Website",
    imgsrc: "/fos.webp",
    link: "https://francwow.github.io/",
    github: "https://github.com/francwow/francwow.github.io",
    id: 6,
    languages: "HTML | CSS",
  },
];
