export const workItems = [
  {
    heading: "Mariposa Azul Website",
    imgsrc: "/mariposa-azul.webp",
    link: "https://mariposa-azul-nextjs.vercel.app/",
    github: "https://github.com/francwow/mariposa-azul-nextjs",
    id: 0,
    languages: "Nextjs | TypeScript | CSS",
  },
  {
    heading: "Donoso Films Website",
    imgsrc: "/donosofilms.webp",
    link: "https://www.donosofilms.com/",
    github: "https://github.com/francwow/donoso-films-nextjs",
    id: 1,
    languages: "Nextjs | TypeScript | CSS",
  },
  {
    heading: "LO Design Website",
    imgsrc: "/lodesign.webp",
    link: "https://www.lodesign.com.co/",
    github: "https://github.com/francwow/lo-design-website-nextjs",
    id: 2,
    languages: "Nextjs | TypeScript | CSS",
  },
  {
    heading: "Hostal Sep7imo Arte Website",
    imgsrc: "/hostal.webp",
    link: "https://hostalsep7imoarte.com/",
    github: "https://github.com/francwow/hostal-septimoarte",
    id: 3,
    languages: "Nextjs | TypeScript | CSS",
  },
  {
    heading: "Depósito San Antonio Website",
    imgsrc: "/deposito.webp",
    link: "https://www.depositosanantonio.com/",
    github: "https://github.com/francwow/DepositoSanAntonio-Website",
    id: 4,
    languages: "HTML | CSS",
  },
  {
    heading: "GreenRoots Website",
    imgsrc: "/green-roots.webp",
    link: "https://green-roots-next-js.vercel.app/",
    github: "https://github.com/francwow/green-roots-next-js.git",
    id: 5,
    languages: "Nextjs | TypeScript | Tailwind CSS",
  },
  {
    heading: "Latiendo Website",
    imgsrc: "/latiendo.webp",
    link: "https://latiendo.vercel.app/",
    github: "https://github.com/francwow/latiendo",
    id: 6,
    languages: "HTML | CSS | JavaScript",
  },
];
